#!/usr/bin/env bash
# a Bash script that listens on port 98 on localhost.
# Ensure the script is run with sudo privileges to bind to port 98

# Start listening on port 98 using netcat (nc)
# The -k option keeps the server running, and -l option listens for incoming connections
nc -lk 98